
- name: Configuring NetScaler to BLOCK and LOG SQL injection attacks on green-app
  hosts: demo_netscalers
  gather_facts: false
  tasks:

    - name: Create Application Firewall Profile
      delegate_to: localhost
      netscaler.adc.appfwprofile:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present

        name: block_log_sql_injection_appfwprofile
        type:
          - HTML
          - JSON
          - XML
        starturlaction:
          - none
        sqlinjectionaction:
          - log
          - block

    - name: Create Application Firewall Policy
      delegate_to: localhost
      netscaler.adc.appfwpolicy:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present

        name: block_log_sql_injection_appfwpolicy
        rule: "HTTP.REQ.URL.STARTSWITH(\"/green\")&&HTTP.REQ.URL.CONTAINS(\"aspx\")"
        profilename: block_log_sql_injection_appfwprofile

    - name: Bind Application Firewall Policy to LB Virtual Server
      delegate_to: localhost
      netscaler.adc.lbvserver_appfwpolicy_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present

        name: lb-green-server
        policyname: block_log_sql_injection_appfwpolicy
        priority: 100
